### ISSUE TITLE
Writing out GridLAB-D model fails after adding house object

### ISSUE THREAD

**Issue by trevorhardy** [pnnl/tesp#96]
Using "feeder_generator_demo.py" in the "api-refactor" branch, I fail to be able to write out the model to file with the following error:

```
/Users/hard312/mambaforge/envs/tesp_feeder_gen/bin/python /Users/hard312/src/TSP/tesp/src/tesp_api/tesp_api/feeder_generator_demo.py 
Opened database successfully
Traceback (most recent call last):
  File "...src/TSP/tesp/src/tesp_api/tesp_api/feeder_generator_demo.py", line 243, in <module>
    _auto_run(args)
  File "....src/TSP/tesp/src/tesp_api/tesp_api/feeder_generator_demo.py", line 217, in _auto_run
    glmMod.write_model("trevor_test.glm")
  File "....src/TSP/tesp/src/tesp_api/tesp_api/modifier.py", line 80, in write_model
    self.model.write(filepath)
  File "....src/TSP/tesp/src/tesp_api/tesp_api/model.py", line 427, in write
    print(self.instancesToGLM(), file=op)
  File "....src/TSP/tesp/src/tesp_api/tesp_api/model.py", line 98, in instancesToGLM
    diction += self.entities[name].instanceToGLM()
  File "....src/TSP/tesp/src/tesp_api/tesp_api/entity.py", line 221, in instanceToGLM
    diction += "  " + item + " " + self.instance[obj_id][item] + ";\n"
TypeError: can only concatenate str (not "float") to str
```

**Comment by trevorhardy** [comment]
Tested with current version and the issue is resolved.
