### ISSUE TITLE
New feeder_generator API fails to read model

### ISSUE THREAD

**Issue by trevorhardy** [pnnl/tesp#97]
The "GLD_three_phase_house.glm" model in the api-refactor branch fails to be read in properly by `GLMModifier.model.read()`.

```
..../mambaforge/envs/tesp_feeder_gen/bin/python ....src/TSP/tesp/src/tesp_api/tesp_api/feeder_generator_demo.py
Opened database successfully
Traceback (most recent call last):
  File "....src/TSP/tesp/src/tesp_api/tesp_api/feeder_generator_demo.py", line 140, in <module>
    _auto_run(args)
  File "....src/TSP/tesp/src/tesp_api/tesp_api/feeder_generator_demo.py", line 88, in _auto_run
    testMod.model.read(feeder_path)
  File "....src/TSP/tesp/src/tesp_api/tesp_api/model.py", line 399, in read
    readresults = self.readBackboneModel(path_parts[1], path_parts[0])
  File "....src/TSP/tesp/src/tesp_api/tesp_api/model.py", line 346, in readBackboneModel
    line, octr, oname, incomments, linecomments = self.obj(None, model, line, itr, h, octr)
  File "....src/TSP/tesp/src/tesp_api/tesp_api/model.py", line 253, in obj
    line, octr = self.obj(oname, model, line, itr, oidh, octr)
ValueError: too many values to unpack (expected 2
```

**Comment by trevorhardy** [comment]
Verified that this issue is resolved.
